---
- name: copy nginx server conf
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/server.conf

- name: enable nginx server conf
  ansible.builtin.file:
    src:  /etc/nginx/sites-available/server.conf
    dest: /etc/nginx/sites-enabled/server.conf
    state: link
  notify: restart nginx

- name: disable nginx default conf
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: enable lets encrypt
  ansible.builtin.shell:
    cmd: certbot -n -m {{ certbot_mail }} --nginx -d {{ ansible_eth0.ipv4.address }}.nip.io --agree-tos {{ certbot_extra_params }}
